version: '3.8'

services:
  # Servicio de base de datos MySQL
  db:
    image: mysql:8.0
    container_name: fintech-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fintech_db
      MYSQL_USER: fintech_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - fintech-network

  # Servicio de backend
  backend:
    build: ./backend
    container_name: fintech-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: fintech_user
      DB_PASSWORD: password
      DB_NAME: fintech_db
    ports:
      - "3000:3000"
    networks:
      - fintech-network

  # Servicio de frontend
  frontend:
    build: ./frontend
    container_name: fintech-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - fintech-network

networks:
  fintech-network:
    driver: bridge

volumes:
  mysql-data: