apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: fintech-app
type: Opaque
data:
  # fintech_user
  mysql-user: ZmludGVjaF91c2Vy
  # password
  mysql-password: cGFzc3dvcmQ=
  # fintech_db
  mysql-database: ZmludGVjaF9kYg==
  # rootpassword
  mysql-root-password: cm9vdHBhc3N3b3Jk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fintech-app
data:
  DB_HOST: "mysql-service"
  NODE_ENV: "production"
  PORT: "3000"
